### PR TITLE
Team Fundator Submission

### PR DESCRIPTION
**Pull request by LM239**
Brief description: U-Net ensembles with 5 weighted models per task, using two different backbones, two different image resolutions, and two different revisions of the MapAI dataset.

Some notes:
    - The submission will not finish in the Github Pipeline due to CPU inference taking more than 6 hours
    - If you have issues downloading with gdown, try updating it to the newest version

### CODE REVIEW

**Comment by Sjyhne** [comment]
Hello! Thank you for your submission. Would you be able to provide all files? Such as training and model definitions?

**Comment by LM239** [comment]
Certainly, we are committed to submitting everything! The training scripts can be run with the shell files in the src/ folder. It will train every model used in the ensembles, and some more used during development. The model definitions are downloaded from Google Drive alongside the model checkpoints, but we can provide them separately if you need.

If you are only interested in training the models used in the ensembles, we could create a separate shell file just for those.

Let me know if anything remains unclear!

**Comment by Sjyhne** [comment]
Oh sorry! My bad. I was supposed to ask this on a different team! Everything seems to be in order here :smile:

**Comment by LM239** [comment]
No worries! With that said, I think it is an unfair advantage if teams are allowed to submit training scripts way after the deadline. They would have more time available to directly improve their score compared to teams who dedicated time during the competition to prepare working scripts, configurations and so on.

**Comment by Sjyhne** [comment]
100% a fair point to make. This fault lies in my description of the competition, as I've not stated whether the model/training definitions must be provided in the original submission or afterward. I'm sorry for being unclear about this matter. 

Appreciate the constructive feedback, and I carry all of the experiences from hosting this competition on to the next one.

**Pull request merged**
